### ISSUE TITLE
YT-1300 icon doesn't work

### ISSUE THREAD

**Issue by guidokessels** [haslo/lists_juggle_browser#39]
It's using the `xwing-miniatures-ship-A-wing` class. It should be `xwing-miniatures-ship-yt1300`.

<img width="440" alt="screen shot 2017-02-15 at 08 48 52" src="https://cloud.githubusercontent.com/assets/834902/22965038/d3ddc236-f35b-11e6-98eb-2a3f0209993f.png">

Seen on http://meta-wing.com/ship_combos?ranking_start=2012-09-14&ranking_end=2017-02-15&large_tournament_multiplier=true&widespread_use_multiplier=true&use_ranking_data=all&tournament_type=1&

**Comment by haslo** [comment]
Thanks!

Heh, you could fix that yourself, by editing the ship. I guess I'll have to hide down that function, people will mess with it otherwise (as has probably happened here).

![screen shot 2017-02-15 at 09 14 54](https://cloud.githubusercontent.com/assets/102580/22965733/407e4a16-f35f-11e6-954d-9592d64585fb.png)

It's fixed for now.

**Comment by haslo** [comment]
👉  #40

**Comment by guidokessels** [comment]
:+1+
