### ISSUE TITLE
Wave 11 Pilots/Ships

### ISSUE THREAD

**Issue by Varthos** [haslo/lists_juggle_browser#71]
Apologies if this has already been asked/answered somewhere else.

When will Wave 11 Pilot/Ships start showing up on meta-wing.com?

Is there a minimum amount of data you need from listjuggler before the db shows list archetypes for them?

Thanks

**Comment by haslo** [comment]
Thanks for the reminder; I'll look into this. Pilots definitely show up as soon as they are sent through the API, but it's possible that ships need some action on my part first.

While I'm at it, I'll also add the C-ROC release and wave 11 to the dropdown.

**Comment by Varthos** [comment]
Forgot to mention Wave 11 upgrades. Dying to see how much success the new cruise missiles and other fun stuff are having!

Thanks for the response looking forward to it.

**Comment by haslo** [comment]
There goes, data imported.

What works now:

* Import of new ships and upgrades in general
* Images are here, too
* Invalid Lists Juggler XWS for two new pilots is fixed upon import

What doesn't:

* Nym has problems because the import doesn't know the rebel version from the scum version (and thus now has rebel pilots in scum lists, yay)
* There are no icons for the new ships yet

I'll get to look into these early next week, probably.

**Comment by haslo** [comment]
Icons are here (I thanked Geordan for the update), the only image I'm aware of missing is Cruise Missile (and Guido knows about that one).

I'll look into the Nym import in the next days (that's #63). That'll improve TIE Fighter and Firespray handling, too.

**Comment by haslo** [comment]
Reopening until I can include https://github.com/guidokessels/xwing-data/pull/116
