### ISSUE TITLE
What the heck do all the numbers mean?

### ISSUE THREAD

**Issue by jlhansen971** [haslo/lists_juggle_browser#82]
So, I may just be very confused because I know nothing about programing, but what the heck do all the numbers mean? What is magic, what is the average percentile telling me? It looks like a great tool, but the labeling can be very confusing for those of us who are not hardcore gamers and have never done a meta analysis before. There should also be a sorting button so we can sort the results, like most played, least played, scum first, etc. Filters should also be more understandable and easier to use. For example I should be able to say I want results from Store Championships and Regionals, but not nationals and vassal (there are two store championship filters btw). Idk, but it just doesn't seem very user friendly or intuitive for new players.

**Comment by haslo** [comment]
Thanks a lot for the feedback 😄 

Yeah, this is just a hobby project, I am working on improving the user interface. Specificially, what you're talking about is, more or less, what these issues are about:

* #4 (Explanation Popups that explain all those numbers)
* #59 (Filters by multiple tournament types) and #70 (Better filters overall)
* #38 (General usability issues) and #43 (Options to sort by different columns)

As such, this issue is pretty much a duplicate and thus I'll probably close it, sorry 😞

Yes, I'm fully aware of these issues, and they are among the things I want to tackle next. But since my free time is limited, I haven't quite gotten around to any of them.

**Comment by haslo** [comment]
Oh, there's also some explanations here, though of course these also could be improved: http://meta-wing.com/about

**Comment by haslo** [comment]
Closing as duplicates then. Thanks again for reporting these.
